info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

spring:
  application.name: ci-droid-tasks-consumer
 # used in case of email notifications are enabled
  mail:
    protocol: smtp
    host: yourMailServer
    port: 25
    sender: ci-droid@yourDomain.com
    smtp:
      auth: false
      starttls.enable: false

# enable below config to be in synchronous mode without messaging bus
#synchronous-mode: true
#spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

#debug: true

hystrix.command.default.execution.timeout.enabled: false
feign.hystrix.enabled: false

source-control:
  type: "GITHUB"
  url: "https://api.github.com"
  apiToken: ${SERVICE_ACCOUNT_API_TOKEN}
#below credentials should be a service account credentials - they will be used to rebase PRs automatically using Git commands.
  login: ${SERVICE_ACCOUNT_GIT_USERNAME:"TBD"}
  password: ${SERVICE_ACCOUNT_GIT_PASSWORD:"TBD"}


notifiers:
  github.prComment.enable: true
#  email.enable: true
#  http.targetUrl: "http://localhost:9901/notify"

cidroid-behavior:
#  whenPushOnDefaultBranch:
  tryToRebaseOpenPrs.enabled: true
  notifyOwnerForNonMergeablePr.enabled: true
  closeOldPullRequests:
    enabled: true
    limitInDays: 180
#  whenPullRequestEvent:
  bestPracticeNotifier.enabled: true
  patternToResourceMapping:
# example of associating a document with a file pattern
    "**/*Dto.java": "https://some_link_to_some_best_practices_repo/noDtoClass.md"
  monitorPushEventOnDefaultBranch: false
  monitorPushEventOnNonDefaultBranch: false
  maxFilesInPRNotifier:
      enabled: true
      maxFiles: 10
      warningMessage: "The PR should not have more than {0} files"


