## put your development specific values in this file

spring:
  rabbitmq:
      addresses: yourRabbitMqServer
      username: guest
      password: guest
      virtual-host: dev

gitHub:
  api.url: "http://api.github.com"
  login: "yourLogin"
  password: "yourPassword"
  oauthToken: "token"

server:
  port: 8081