## put your development specific values in this file

spring:
  rabbitmq:
    ssl.enabled: false


source-control:
  type: "GITHUB"
  url: "http://api.github.com"
  login: "yourLogin"
  password: "yourPassword"
  oauthToken: "token"

server:
  port: 8081