## put your development specific values in this file

spring:
  rabbitmq:
    ssl.enabled: false

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

synchronous-mode: true

source-control:
  type: "GITLAB"
  url: "http://gitlab.it.gefa.de"
  login: "yourLogin"
  password: "yourPassword"
  apiToken: "ppr1znVKgzSTJaCwKHTw"

cidroid-behavior:
  bestPracticeNotifier:
    enabled: false

server:
  port: 8081